Fix_Issues_Django/korabco/korabco/account/urls.py
# Core Django imports.
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from account.views import (
    UserLoginView,
    UserLogoutView,
    ActivateView,
    AccountActivationSentView,
    UserRegisterView,
    ProfileUpdatedView,
)

app_name = "account"

urlpatterns = [
    # Account
    path(route='login/', view=UserLoginView.as_view(), name='login'),
    path(route='register/', view=UserRegisterView.as_view(), name='register'),
    path(route='logout/', view=UserLogoutView.as_view(), name='logout'),
    path(route='activation_sent/', view=AccountActivationSentView.as_view(), name='activation_sent'),
    path(route='activate/<uidb64>/<token>/', view=ActivateView.as_view(), name='activate'),
    path(route='profile/update/', view=ProfileUpdatedView.as_view(), name='profile_update'),

    # Password Reset
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='account/password_reset.html',
                                              subject_template_name='mails/password_reset_subject.txt',
                                              email_template_name='mails/password_reset_email.html',
                                              html_email_template_name='mails/password_reset_email.html',
                                              success_url=reverse_lazy('account:password_reset_done')),
                                              name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html',
                                                     success_url=reverse_lazy('account:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
         name='password_reset_complete'),
]

Fix_Issues_Django/korabco/korabco/dashboard/urls.py
from django.urls import path

from dashboard.views import (
    DashboardView,
    BooksView,
    CreateBookView,
    UpdateBookView,
    DeleteBookView,
    BookReviewUrlsView,
    CheckReviewBookView,
    SubmitReviewBookView,
    ValidateReviewBookView,
    GetBookQuestionsView,
    ProofBookByAnswerQuestionView,
    BookQuestionsView,
    CreateQuestionView,
    UpdateQuestionView,
    DeleteQuestionView,
    ReportsView,
)

app_name = "dashboard"


urlpatterns = [
    path(route='', view=DashboardView.as_view(), name='home'),

    path(route='books/', view=BooksView.as_view(), name='books'),
    path(route='book/create/', view=CreateBookView.as_view(), name='create_book'),
    path(route='book/<pk>/update/', view=UpdateBookView.as_view(), name='update_book'),
    path(route='book/<book_id>/delete/', view=DeleteBookView.as_view(), name='delete_book'),

    path(route='book/<book_id>/questions/', view=BookQuestionsView.as_view(), name="book_questions"),
    path(route='book/<book_id>/get/questions/', view=GetBookQuestionsView.as_view(), name="book_get_questions"),
    path(route='book/<book_id>/question/create/', view=CreateQuestionView.as_view(), name='create_question'),
    path(route='book/question/<book_question_id>/update/', view=UpdateQuestionView.as_view(), name='update_question'),
    path(route='book/question/<book_question_id>/delete/', view=DeleteQuestionView.as_view(), name='delete_question'),
    path(route='book/question/<book_question_id>/proof/', view=ProofBookByAnswerQuestionView.as_view(), name="proof_book"),

    path(route='book/review-urls/', view=BookReviewUrlsView.as_view(), name="book_review_urls"),
    path(route='book/<book_id>/check/review-url/', view=CheckReviewBookView.as_view(), name='check_review_book'),
    path(route='book/<book_id>/submit/review-url/', view=SubmitReviewBookView.as_view(), name='submit_review_book'),
    path(route='book/<book_id>/validate/review-url/', view=ValidateReviewBookView.as_view(), name='validate_review_book'),

    path(route='<model_name>/reports/', view=ReportsView.as_view(), name='reports'),

]

Fix_Issues_Django/korabco/korabco/korabco/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from django.contrib import admin

from .views import HomeView

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = i18n_patterns(
    # path("", HomeView.as_view(), name="home"),
    path('account/', include('account.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path(r'', include('cms.urls')),

)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Fix_Issues_Django/korabco/korabco/korabco/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'korabco/cms/pages/home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        return context

Fix_Issues_Django/korabco/korabco/korabco/templates/korabco/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block head_title %}Korabco{% endblock head_title %}</title>

    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'images/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'images/favicon/safari-pinned-tab.svg" color="#5bbad5' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <!-- core CSS -->
    <link href="{% static 'korabco/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'korabco/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'korabco/css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'korabco/css/main.css' %}" rel="stylesheet">
    <link href="{% static 'korabco/css/responsive.css' %}" rel="stylesheet">

    {% block css %}{% endblock css %}

    <!--[if lt IE 9]>
    <script src="{% static 'korabco/js/html5shiv.js' %}"></script>
    <script src="{% static 'korabco/js/respond.min.js' %}"></script>
    <![endif]-->
    <link rel="shortcut icon" href="images/ico/favicon.ico">
</head>
<!--/head-->

<body class="homepage">

    {% include 'korabco/header.html' %}

    {% block content %}{% endblock content %}

    {% include 'korabco/footer.html' %}

    <script src="{% static 'korabco/js/jquery.js' %}"></script>
    <script src="{% static 'korabco/js/bootstrap.min.js' %}"></script>

    {% block js %}{% endblock js %}
</body>

</html>

Fix_Issues_Django/korabco/korabco/korabco/templates/korabco/cms_base.html
{% load i18n cms_tags sekizai_tags menu_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'images/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'images/favicon/safari-pinned-tab.svg" color="#5bbad5' %}">
    <link rel="shortcut icon" href="images/ico/favicon.ico">


    {% block meta_tags %}{% endblock %}

    {% render_block "css" %}

    {% block base_stylesheet %}
        <!-- core CSS -->
        <link href="{% static 'korabco/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'korabco/css/font-awesome.min.css' %}" rel="stylesheet">
        <link href="{% static 'korabco/css/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'korabco/css/main.css' %}" rel="stylesheet">
        <link href="{% static 'korabco/css/responsive.css' %}" rel="stylesheet">
    {% endblock %}

    {% block css %}{% endblock css %}

    <!--[if lt IE 9]>
    <script src="{% static 'korabco/js/html5shiv.js' %}"></script>
    <script src="{% static 'korabco/js/respond.min.js' %}"></script>
    <![endif]-->
</head>
<!--/head-->

<body class="homepage">

    {% cms_toolbar %}


    {% block page %}

        {% include 'korabco/header.html' %}

        {% block content %}{% endblock content %}

        {% include 'korabco/footer.html' %}

    {% endblock %}

    {% block base_js %}
        <script src="{% static 'korabco/js/jquery.js' %}"></script>
        <script src="{% static 'korabco/js/bootstrap.min.js' %}"></script>
    {% endblock %}

    {% render_block "js" %}

    {% block js %}{% endblock js %}
</body>

</html>

Fix_Issues_Django/korabco/korabco/korabco/templates/korabco/footer.html
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="text-center">
                © 2022 <a target="_blank" href="{{ SITE_URL }}"><span style="color: #e93424">K</span>orabco</a>. All Rights Reserved.
            </div>
        </div>
    </div>
</footer>

Fix_Issues_Django/korabco/korabco/korabco/templates/korabco/header.html
{% load static %}
{% load i18n cms_tags sekizai_tags menu_tags %}
<header id="header">
    <nav class="navbar navbar-inverse" role="banner">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ SITE_URL }}">
                    <img width="148px" src="{% static 'korabco/images/logo.png' %}" alt="logo">
                </a>
            </div>

            <div class="collapse navbar-collapse navbar-right">
                <ul class="nav navbar-nav">
                    {% show_menu 0 100 100 100 "menu/menu.html" %}
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'dashboard:home' %}">Dashboard</a></li>
                        <li><a href="{% url 'account:logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'account:login' %}">Login</a></li>
                        <li><a href="{% url 'account:register' %}">Register</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
        <!--/.container-->
    </nav>
    <!--/nav-->

</header>
<!--/header-->