Fix_Issues_Django/korabco/korabco/account/urls.py
# Core Django imports.
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from account.views import (
    UserLoginView,
    UserLogoutView,
    ActivateView,
    AccountActivationSentView,
    UserRegisterView,
    ProfileUpdatedView,
)

app_name = "account"

urlpatterns = [
    # Account
    path(route='login/', view=UserLoginView.as_view(), name='login'),
    path(route='register/', view=UserRegisterView.as_view(), name='register'),
    path(route='logout/', view=UserLogoutView.as_view(), name='logout'),
    path(route='activation_sent/', view=AccountActivationSentView.as_view(), name='activation_sent'),
    path(route='activate/<uidb64>/<token>/', view=ActivateView.as_view(), name='activate'),
    path(route='profile/update/', view=ProfileUpdatedView.as_view(), name='profile_update'),

    # Password Reset
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='account/password_reset.html',
                                              subject_template_name='mails/password_reset_subject.txt',
                                              email_template_name='mails/password_reset_email.html',
                                              html_email_template_name='mails/password_reset_email.html',
                                              success_url=reverse_lazy('account:password_reset_done')),
                                              name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html',
                                                     success_url=reverse_lazy('account:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
         name='password_reset_complete'),
]

Fix_Issues_Django/korabco/korabco/dashboard/urls.py
from django.urls import path

from dashboard.views import (
    DashboardView,
    BooksView,
    CreateBookView,
    UpdateBookView,
    DeleteBookView,
    BookReviewUrlsView,
    CheckReviewBookView,
    SubmitReviewBookView,
    ValidateReviewBookView,
    GetBookQuestionsView,
    ProofBookByAnswerQuestionView,
    BookQuestionsView,
    CreateQuestionView,
    UpdateQuestionView,
    DeleteQuestionView,
    ReportsView,
)

app_name = "dashboard"


urlpatterns = [
    path(route='', view=DashboardView.as_view(), name='home'),

    path(route='books/', view=BooksView.as_view(), name='books'),
    path(route='book/create/', view=CreateBookView.as_view(), name='create_book'),
    path(route='book/<pk>/update/', view=UpdateBookView.as_view(), name='update_book'),
    path(route='book/<book_id>/delete/', view=DeleteBookView.as_view(), name='delete_book'),

    path(route='book/<book_id>/questions/', view=BookQuestionsView.as_view(), name="book_questions"),
    path(route='book/<book_id>/get/questions/', view=GetBookQuestionsView.as_view(), name="book_get_questions"),
    path(route='book/<book_id>/question/create/', view=CreateQuestionView.as_view(), name='create_question'),
    path(route='book/question/<book_question_id>/update/', view=UpdateQuestionView.as_view(), name='update_question'),
    path(route='book/question/<book_question_id>/delete/', view=DeleteQuestionView.as_view(), name='delete_question'),
    path(route='book/question/<book_question_id>/proof/', view=ProofBookByAnswerQuestionView.as_view(), name="proof_book"),

    path(route='book/review-urls/', view=BookReviewUrlsView.as_view(), name="book_review_urls"),
    path(route='book/<book_id>/check/review-url/', view=CheckReviewBookView.as_view(), name='check_review_book'),
    path(route='book/<book_id>/submit/review-url/', view=SubmitReviewBookView.as_view(), name='submit_review_book'),
    path(route='book/<book_id>/validate/review-url/', view=ValidateReviewBookView.as_view(), name='validate_review_book'),

    path(route='<model_name>/reports/', view=ReportsView.as_view(), name='reports'),

]

Fix_Issues_Django/korabco/korabco/korabco/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from django.contrib import admin

from .views import HomeView

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = i18n_patterns(
    # path("", HomeView.as_view(), name="home"),
    path('account/', include('account.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path(r'', include('cms.urls')),

)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Fix_Issues_Django/korabco/korabco/dashboard/forms.py
from django.forms import ModelForm
from dashboard.models import Book


class CreateBookForm(ModelForm):
    prefix = 'create'

    class Meta:
        model = Book
        fields = ('code', 'title', 'app_url', 'mp3_file')


class UpdateBookForm(ModelForm):
    prefix = 'update'

    class Meta:
        model = Book
        fields = ('code', 'title', 'app_url', 'mp3_file')

Fix_Issues_Django/korabco/korabco/dashboard/views.py
import json

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import EmailMultiAlternatives
from django.forms import model_to_dict
from django.http import JsonResponse
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, View, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from dashboard.models import Book, MyBook, BookQuestion
from dashboard.forms import CreateBookForm, UpdateBookForm
from dashboard.mixins import SuperUserRequiredMixin

import datetime

REVIEW_URLS = [
    'amazon.com',
    'amazon.in',
    'amazon.co.uk',
    'amazon.de',
    'amazon.fr',
    'amazon.es',
    'amazon.it',
    'amazon.nl',
    'amazon.co.jp',
    'amazon.com.br',
    'amazon.ca',
    'amazon.com.mx',
    'amazon.com.au',
]


def get_rotate_questions(book_questions):
    day_today = datetime.datetime.today().day
    days_question1 = [1, 11, 21, 31]
    days_question2 = [2, 12, 22]
    days_question3 = [3, 13, 23]
    days_question4 = [4, 14, 24]
    days_question5 = [5, 15, 25]
    days_question6 = [6, 16, 26]
    days_question7 = [7, 17, 27]
    days_question8 = [8, 18, 28]
    days_question9 = [9, 19, 29]
    days_question10 = [10, 20, 30]

    if day_today in days_question1:
        return book_questions[0]
    elif day_today in days_question2:
        return book_questions[1]
    elif day_today in days_question3:
        return book_questions[2]
    elif day_today in days_question4:
        return book_questions[3]
    elif day_today in days_question5:
        return book_questions[4]
    elif day_today in days_question6:
        return book_questions[5]
    elif day_today in days_question7:
        return book_questions[6]
    elif day_today in days_question8:
        return book_questions[7]
    elif day_today in days_question9:
        return book_questions[8]
    elif day_today in days_question10:
        return book_questions[9]
    else:
        return None


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard/home.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        if self.request.user.is_superuser:
            queryset = MyBook.objects.all().order_by('-created_at')
        else:
            queryset = MyBook.objects.filter(user=self.request.user).order_by('-created_at')
        context['queryset'] = queryset
        context['books'] = Book.objects.all().order_by('-created_at')
        return context


class BooksView(SuperUserRequiredMixin, ListView):
    model = Book
    context_object_name = 'books'
    template_name = 'dashboard/books.html'

    def get_queryset(self):
        return Book.objects.all().order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super(BooksView, self).get_context_data(**kwargs)
        context['form_create'] = CreateBookForm()
        context['form_update'] = UpdateBookForm()
        return context


class CreateBookView(SuperUserRequiredMixin, SuccessMessageMixin, CreateView):
    model = Book
    form_class = CreateBookForm
    template_name = 'dashboard/books.html'
    success_url = reverse_lazy('dashboard:books')
    success_message = 'Your Book has been added successfully'

    def form_invalid(self, form):
        json_errors = form.errors.as_json()
        json_errors = json.loads(json_errors)
        for key in json_errors:
            msg_error = json_errors[key][0]['message']
            messages.error(self.request, msg_error)

        return redirect('dashboard:books')


class UpdateBookView(SuperUserRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Book
    form_class = UpdateBookForm
    template_name = 'dashboard/books.html'
    success_url = reverse_lazy('dashboard:books')
    success_message = 'Your Book has been updated successfully'

    def form_invalid(self, form):
        json_errors = form.errors.as_json()
        json_errors = json.loads(json_errors)
        for key in json_errors:
            msg_error = json_errors[key][0]['message']
            messages.error(self.request, msg_error)

        return redirect('dashboard:books')


class DeleteBookView(SuperUserRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        json_response = {"success": False}
        try:
            book_id = kwargs.get('book_id')
            book = Book.objects.filter(id=book_id).first()
            if book:
                book.delete()
                json_response['success'] = True
                json_response['message'] = 'Your Book has been deleted successfully'
            else:
                json_response['message'] = 'This book does not exist'

        except Exception as e:
            json_response['error'] = str(e)
            json_response['message'] = 'Error while removing the book, please try again'

        return JsonResponse(json_response)


class BookQuestionsView(SuperUserRequiredMixin, ListView):
    model = BookQuestion
    context_object_name = 'questions'
    template_name = 'dashboard/questions.html'

    def get_context_data(self, **kwargs):
        context = super(BookQuestionsView, self).get_context_data(**kwargs)
        book_id = self.kwargs.get('book_id')
        book = Book.objects.get(id=book_id)
        context['book_code'] = book.code
        return context

    def get_queryset(self):
        book_id = self.kwargs.get('book_id')
        return BookQuestion.objects.filter(book_id=book_id).order_by('-created_at')


class GetBookQuestionsView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        json_response = {"success": False}
        try:
            book_id = kwargs.get('book_id')
            book_questions = BookQuestion.objects.filter(book_id=book_id).order_by('created_at')
            book_question = get_rotate_questions(book_questions)
            if book_question:
                json_response['data'] = {'question': book_question.question, 'id': book_question.id}
                json_response['success'] = True
            else:
                json_response['message'] = 'This Book has no questions yet'

        except Exception as e:
            json_response['error'] = str(e)
            json_response['message'] = 'Error while getting the questions of this book'

        return JsonResponse(json_response)


class ProofBookByAnswerQuestionView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        json_response = {"success": False}
        try:
            book_question_id = self.kwargs.get('book_question_id')
            answer = request.POST['answer']
            book_question = BookQuestion.objects.get(id=book_question_id)
            if book_question:
                if book_question.answer == answer:
                    MyBook.objects.create(user=request.user, book=book_question.book)
                    json_response['success'] = True
                    msg = "Your Book has been added successfully to your list 'My-Books'"
                    messages.success(request, msg)
                else:
                    json_response['message'] = 'Wrong answer - Please try again.'
            else:
                json_response['message'] = 'Error while getting the questions of this book.'

        except Exception as e:
            json_response['error'] = str(e)
            json_response['message'] = 'Error while adding the book to your list, please try again'

        return JsonResponse(json_response)


class CreateQuestionView(SuperUserRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        json_response = {"success": False}
        try:
            book_id = self.kwargs.get('book_id')
            question = request.POST['question']
            answer = request.POST['answer']
            count_books = BookQuestion.objects.filter(book_id=book_id).count()
            if count_books >= 10:
                json_response['message'] = 'You have saved more than 10 questions for this book ... ' \
                                           'please remove one question before you add a new one !'
            else:
                book_question = BookQuestion.objects.create(question=question, answer=answer, book_id=book_id)
                book_question_dict = model_to_dict(book_question)
                book_question_dict['book'] = book_question.book.code
                json_response['book_question'] = book_question_dict
                json_response['success'] = True
                json_response['message'] = 'Your Question has been added successfully'
        except Exception as e:
            json_response['error'] = str(e)
            json_response['message'] = 'Error while saving the question, please try again'

        return JsonResponse(json_response)


class UpdateQuestionView(SuperUserRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        json_response = {"success": False}
        try:
            book_question_id = kwargs.get('book_question_id')
            question = request.POST['question']
            answer = request.POST['answer']

            book_question = BookQuestion.objects.get(id=book_question_id)
            book_question.question = question
            book_question.answer = answer
            book_question.save()
            json_response['success'] = True
            json_response['message'] = 'Your Question has been updated successfully'
        except Exception as e:
            json_response['error'] = str(e)
            json_response['message'] = 'Error while updating the question, please try again'

        return JsonResponse(json_response)


class DeleteQuestionView(SuperUserRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        json_response = {"success": False}
        try:

Fix_Issues_Django/korabco/korabco/korabco/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'korabco/cms/pages/home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        return context

Fix_Issues_Django/korabco/korabco/korabco/templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8"/>
    <meta charset="utf-8"/>
    <title>{% block head_title %}Dashboard{% endblock head_title %}</title>
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no"/>
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'images/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'images/favicon/safari-pinned-tab.svg" color="#5bbad5' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <link href="{% static 'dashboard/plugins/pace/pace-theme-flash.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'dashboard/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'dashboard/plugins/font-awesome/css/font-awesome.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'dashboard/plugins/jquery-scrollbar/jquery.scrollbar.css' %}" rel="stylesheet" type="text/css" media="screen"/>
    <link href="{% static 'dashboard/plugins/select2/css/select2.min.css' %}" rel="stylesheet" type="text/css" media="screen"/>
    <link href="{% static 'dashboard/plugins/switchery/css/switchery.min.css' %}" rel="stylesheet" type="text/css" media="screen"/>
    <link href="{% static 'dashboard/plugins/jquery-datatable/media/css/dataTables.bootstrap.min.css' %}" rel="stylesheet"
          type="text/css"/>
    <link href="{% static 'dashboard/plugins/jquery-datatable/extensions/FixedColumns/css/dataTables.fixedColumns.min.css' %}"
          rel="stylesheet" type="text/css"/>
    <link href="{% static 'dashboard/plugins/datatables-responsive/css/datatables.responsive.css' %}" rel="stylesheet" type="text/css"
          media="screen"/>
    <link href="{% static 'dashboard/pages/css/pages-icons.css' %}" rel="stylesheet" type="text/css">
    <link class="main-stylesheet" href="{% static 'dashboard/pages/css/themes/modern.css' %}" rel="stylesheet" type="text/css"/>
    {% block extra-css %}{% endblock %}
</head>
<body class="fixed-header horizontal-menu horizontal-app-menu ">

<div class="header p-r-0 bg-primary-black">

    {% include 'dashboard/includes/header.html' %}

    {% include 'dashboard/includes/navbar.html' %}

</div>
<div class="page-container ">
    <!-- START PAGE CONTENT WRAPPER -->
    <div class="page-content-wrapper ">

        <!-- START PAGE CONTENT -->
        {% block content %}{% endblock %}
        <!-- END PAGE CONTENT -->

        <!-- START FOOTER -->
        {% include 'dashboard/includes/footer.html' %}
        <!-- END FOOTER -->

        <!-- Messages -->
        {% block messages %}
            <div class="pgn-wrapper" data-position="top" style="top: 95px;">
                {% for message in messages %}
                    <div class="pgn push-on-sidebar-open pgn-bar">
                        <div class="alert {% if message.level_tag == 'error' %}alert-danger{% else %}alert-{{ message.tags }}{% endif %}">
                            <div class="container">
                                <span>{{ message }}</span>
                                <button type="button" class="close" data-dismiss="alert">
                                    <span aria-hidden="true">×</span>
                                    <span class="sr-only">Close</span>
                                </button>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endblock messages %}

    </div>
    <!-- END PAGE CONTENT WRAPPER -->
</div>

<!-- BEGIN VENDOR JS -->
<script src="{% static 'dashboard/plugins/pace/pace.min.js' %}" type="text/javascript"></script>
<script src="{% static 'dashboard/plugins/jquery/jquery-3.2.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'dashboard/plugins/modernizr.custom.js' %}" type="text/javascript"></script>
<script src="{% static 'dashboard/plugins/jquery-ui/jquery-ui.min.js' %}" type="text/javascript"></script>
<script src="{% static 'dashboard/plugins/popper/umd/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'dashboard/plugins/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'dashboard/plugins/jquery/jquery-easy.js' %}" type="text/javascript"></script>
<script src="{% static 'dashboard/plugins/jquery-unveil/jquery.unveil.min.js' %}" type="text/javascript"></script>
<script src="{% static 'dashboard/plugins/jquery-ios-list/jquery.ioslist.min.js' %}" type="text/javascript"></script>
<script src="{% static 'dashboard/plugins/jquery-actual/jquery.actual.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/jquery-scrollbar/jquery.scrollbar.min.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/plugins/select2/js/select2.full.min.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/plugins/classie/classie.js' %}"></script>
<script src="{% static 'dashboard/plugins/switchery/js/switchery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'dashboard/plugins/jquery-validation/js/jquery.validate.min.js' %}" type="text/javascript"></script>
<script src="{% static 'dashboard/plugins/jquery-datatable/media/js/jquery.dataTables.min.js' %}" type="text/javascript"></script>
<script src="{% static 'dashboard/plugins/jquery-datatable/extensions/TableTools/js/dataTables.tableTools.min.js' %}"
        type="text/javascript"></script>
<script src="{% static 'dashboard/plugins/jquery-datatable/media/js/dataTables.bootstrap.js' %}" type="text/javascript"></script>
<script src="{% static 'dashboard/plugins/jquery-datatable/extensions/Bootstrap/jquery-datatable-bootstrap.js' %}"
        type="text/javascript"></script>
<script type="text/javascript" src="{% static 'dashboard/plugins/datatables-responsive/js/datatables.responsive.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/plugins/datatables-responsive/js/lodash.min.js' %}"></script>
<!-- END VENDOR JS -->
<!-- BEGIN CORE TEMPLATE JS -->
<script src="{% static 'dashboard/pages/js/pages.js' %}"></script>
<!-- END CORE TEMPLATE JS -->
{% block extra-js %}{% endblock %}
</body>
</html>

Fix_Issues_Django/korabco/korabco/korabco/templates/dashboard/review_urls.html
{% extends "dashboard/base.html" %}

{% load static %}

{% block head_title %}{{ block.super }} | ReviewUrls {% endblock head_title %}

{% block extra-css %}
    <style>
    table tr:hover {
        cursor: pointer;
    }
    </style>
{% endblock %}

{% block content %}
    <div class="content ">

        <div class="bg-white">
            <div class="container">
                <ol class="breadcrumb breadcrumb-alt">
                    <li class="breadcrumb-item"><a href="{{ SITE_URL }}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'dashboard:home' %}">Dashboard</a></li>
                    <li class="breadcrumb-item">ReviewURLs</li>
                </ol>
            </div>
        </div>

        {% include 'dashboard/includes/jumbotron.html' %}

        <!-- START CONTAINER FLUID -->
        <div class=" container-fixed-lg bg-white">
            <div class="container">
                <!-- START card -->
                <div class="card card-transparent">
                    <div class="card-header ">
                        <div class="card-title">All Books with their ReviewUrls
                        </div>
                        <div class="pull-right">
                            <div class="col-xs-12">
                                <button id="allReviewsBtn" class="btn btn-outline-danger btn-cons">ALL</button>
                                <button id="unvalidatedReviewsBtn" class="btn btn-outline-warning btn-cons">UNVALIDATED</button>
                            </div>
                        </div>
                        <br><br><br>
                        <div class="pull-right">
                            <div class="col-xs-12">
                              <input type="text" id="search-table" class="form-control pull-right" placeholder="Search">
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover" id="tableWithSearch">
                                <thead>
                                <tr>
                                    <th>User</th>
                                    <th>Code</th>
                                    <th>ReviewUrl</th>
                                    <th>ReviewDate</th>
                                    <th>ReviewCheck</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for entry in queryset %}
                                    <tr>
                                        <td class="v-align-middle ">
                                            <p>{{ entry.user.email }}</p>
                                        </td>
                                        <td class="v-align-middle ">
                                            <p>{{ entry.book.code }}</p>
                                        </td>
                                        <td class="v-align-middle ">
                                            <p>
                                                {% if entry.review_url %}
                                                    <a href="{{ entry.review_url }}" target="_blank">{{ entry.review_url }}</a>
                                                {% else %}
                                                    --
                                                {% endif %}
                                            </p>
                                        </td>
                                        <td class="v-align-middle">
                                            <p>{{ entry.review_date|default_if_none:"--" }}</p>
                                        </td>
                                        <td class="v-align-middle">
                                            <p>
                                                <span class="{% if entry.review_check %}bg-success-dark{% else %}bg-danger-dark{% endif %} text-white font-weight-bold px-2 py-2">
                                                        {{ entry.review_check }}
                                                </span>
                                            </p>
                                        </td>
                                        <td class="v-align-middle">
                                            <p>
                                                {% if not entry.review_check %}
                                                <a data-id="{{ entry.id }}" class="text-warning validate-review-url" href="#" data-placement="top" data-toggle="tooltip" data-original-title="Validate Review">
                                                    <i class="fa fa-clock-o"></i>
                                                </a>&nbsp;
                                                {% else %}
                                                    <i class="fa fa-check text-success" data-placement="top" data-toggle="tooltip" data-original-title="Checked!"></i>
                                                {% endif %}
                                            </p>
                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- END card -->
            </div>

        </div>
        <!-- END CONTAINER FLUID -->
    </div>
{% endblock %}

{% block extra-js %}
    <script>
        $(document).ready(function () {

            // Function reload page
            function reloadPage(){
                if (window.location.href.indexOf('?') > -1) {
                    window.location.href = window.location.pathname;
                }else{
                    window.location.reload();
                }
            }

            // Click button All ReviewURLs
            $('#allReviewsBtn').click(function () {
                reloadPage();
            });

            // Click button Unvalidated ReviewsURLs
            $('#unvalidatedReviewsBtn').click(function () {
                var currentLocation = String(window.location);
                if (currentLocation.indexOf('?unvalidated=1') === -1) window.location.href = currentLocation + '?unvalidated=1';
                else window.location.href = currentLocation
            });

            // Initialize datatable showing a search box at the top right corner
            var initTableWithSearch = function() {
                var table = $('#tableWithSearch');

                var settings = {
                    "sDom": "<t><'row'<p i>>",
                    "destroy": true,
                    "scrollCollapse": true,
                    "oLanguage": {
                        "sLengthMenu": "_MENU_ ",
                        "sInfo": "Showing <b>_START_ to _END_</b> of _TOTAL_ entries"
                    },
                    "iDisplayLength": 5,
                    "ordering": false
                };

                table.dataTable(settings);

                // search box for table
                $('#search-table').keyup(function() {
                    table.fnFilter($(this).val());
                });
            }

            initTableWithSearch();

            // Validate ReviewURL click
            $('.validate-review-url').click(function (e) {

                e.preventDefault();
                const bookId = $(this).data('id');
                const url = "{% url 'dashboard:validate_review_book' 1 %}".replace(1, bookId);
                var payload = {
                    'csrfmiddlewaretoken': "{{ csrf_token }}",
                };
                $.post(url, payload).done(function (response) {
                    if (response.success) {
                        console.log("success : ", response);
                        reloadPage();
                    } else {
                        console.log('error : ', response.error);
                        reloadPage();
                    }
                }).fail(function (res) {
                    console.log('error : ', res.error);
                });

            });
        });
    </script>

{% endblock %}