Fix_Issues_Django/korabco/korabco/account/urls.py
# Core Django imports.
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from account.views import (
    UserLoginView,
    UserLogoutView,
    ActivateView,
    AccountActivationSentView,
    UserRegisterView,
    ProfileUpdatedView,
)

app_name = "account"

urlpatterns = [
    # Account
    path(route='login/', view=UserLoginView.as_view(), name='login'),
    path(route='register/', view=UserRegisterView.as_view(), name='register'),
    path(route='logout/', view=UserLogoutView.as_view(), name='logout'),
    path(route='activation_sent/', view=AccountActivationSentView.as_view(), name='activation_sent'),
    path(route='activate/<uidb64>/<token>/', view=ActivateView.as_view(), name='activate'),
    path(route='profile/update/', view=ProfileUpdatedView.as_view(), name='profile_update'),

    # Password Reset
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='account/password_reset.html',
                                              subject_template_name='mails/password_reset_subject.txt',
                                              email_template_name='mails/password_reset_email.html',
                                              html_email_template_name='mails/password_reset_email.html',
                                              success_url=reverse_lazy('account:password_reset_done')),
                                              name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html',
                                                     success_url=reverse_lazy('account:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
         name='password_reset_complete'),
]

Fix_Issues_Django/korabco/korabco/dashboard/urls.py
from django.urls import path

from dashboard.views import (
    DashboardView,
    BooksView,
    CreateBookView,
    UpdateBookView,
    DeleteBookView,
    BookReviewUrlsView,
    CheckReviewBookView,
    SubmitReviewBookView,
    ValidateReviewBookView,
    GetBookQuestionsView,
    ProofBookByAnswerQuestionView,
    BookQuestionsView,
    CreateQuestionView,
    UpdateQuestionView,
    DeleteQuestionView,
    ReportsView,
)

app_name = "dashboard"


urlpatterns = [
    path(route='', view=DashboardView.as_view(), name='home'),

    path(route='books/', view=BooksView.as_view(), name='books'),
    path(route='book/create/', view=CreateBookView.as_view(), name='create_book'),
    path(route='book/<pk>/update/', view=UpdateBookView.as_view(), name='update_book'),
    path(route='book/<book_id>/delete/', view=DeleteBookView.as_view(), name='delete_book'),

    path(route='book/<book_id>/questions/', view=BookQuestionsView.as_view(), name="book_questions"),
    path(route='book/<book_id>/get/questions/', view=GetBookQuestionsView.as_view(), name="book_get_questions"),
    path(route='book/<book_id>/question/create/', view=CreateQuestionView.as_view(), name='create_question'),
    path(route='book/question/<book_question_id>/update/', view=UpdateQuestionView.as_view(), name='update_question'),
    path(route='book/question/<book_question_id>/delete/', view=DeleteQuestionView.as_view(), name='delete_question'),
    path(route='book/question/<book_question_id>/proof/', view=ProofBookByAnswerQuestionView.as_view(), name="proof_book"),

    path(route='book/review-urls/', view=BookReviewUrlsView.as_view(), name="book_review_urls"),
    path(route='book/<book_id>/check/review-url/', view=CheckReviewBookView.as_view(), name='check_review_book'),
    path(route='book/<book_id>/submit/review-url/', view=SubmitReviewBookView.as_view(), name='submit_review_book'),
    path(route='book/<book_id>/validate/review-url/', view=ValidateReviewBookView.as_view(), name='validate_review_book'),

    path(route='<model_name>/reports/', view=ReportsView.as_view(), name='reports'),

]

Fix_Issues_Django/korabco/korabco/korabco/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from django.contrib import admin

from .views import HomeView

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = i18n_patterns(
    # path("", HomeView.as_view(), name="home"),
    path('account/', include('account.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path(r'', include('cms.urls')),

)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Fix_Issues_Django/korabco/korabco/dashboard/forms.py
from django.forms import ModelForm
from dashboard.models import Book


class CreateBookForm(ModelForm):
    prefix = 'create'

    class Meta:
        model = Book
        fields = ('code', 'title', 'app_url', 'mp3_file')


class UpdateBookForm(ModelForm):
    prefix = 'update'

    class Meta:
        model = Book
        fields = ('code', 'title', 'app_url', 'mp3_file')

Fix_Issues_Django/korabco/korabco/dashboard/views.py
import json

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import EmailMultiAlternatives
from django.forms import model_to_dict
from django.http import JsonResponse
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, View, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from dashboard.models import Book, MyBook, BookQuestion
from dashboard.forms import CreateBookForm, UpdateBookForm
from dashboard.mixins import SuperUserRequiredMixin

import datetime

REVIEW_URLS = [
    'amazon.com',
    'amazon.in',
    'amazon.co.uk',
    'amazon.de',
    'amazon.fr',
    'amazon.es',
    'amazon.it',
    'amazon.nl',
    'amazon.co.jp',
    'amazon.com.br',
    'amazon.ca',
    'amazon.com.mx',
    'amazon.com.au',
]


def get_rotate_questions(book_questions):
    day_today = datetime.datetime.today().day
    days_question1 = [1, 11, 21, 31]
    days_question2 = [2, 12, 22]
    days_question3 = [3, 13, 23]
    days_question4 = [4, 14, 24]
    days_question5 = [5, 15, 25]
    days_question6 = [6, 16, 26]
    days_question7 = [7, 17, 27]
    days_question8 = [8, 18, 28]
    days_question9 = [9, 19, 29]
    days_question10 = [10, 20, 30]

    if day_today in days_question1:
        return book_questions[0]
    elif day_today in days_question2:
        return book_questions[1]
    elif day_today in days_question3:
        return book_questions[2]
    elif day_today in days_question4:
        return book_questions[3]
    elif day_today in days_question5:
        return book_questions[4]
    elif day_today in days_question6:
        return book_questions[5]
    elif day_today in days_question7:
        return book_questions[6]
    elif day_today in days_question8:
        return book_questions[7]
    elif day_today in days_question9:
        return book_questions[8]
    elif day_today in days_question10:
        return book_questions[9]
    else:
        return None


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard/home.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        if self.request.user.is_superuser:
            queryset = MyBook.objects.all().order_by('-created_at')
        else:
            queryset = MyBook.objects.filter(user=self.request.user).order_by('-created_at')
        context['queryset'] = queryset
        context['books'] = Book.objects.all().order_by('-created_at')
        return context


class BooksView(SuperUserRequiredMixin, ListView):
    model = Book
    context_object_name = 'books'
    template_name = 'dashboard/books.html'

    def get_queryset(self):
        return Book.objects.all().order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super(BooksView, self).get_context_data(**kwargs)
        context['form_create'] = CreateBookForm()
        context['form_update'] = UpdateBookForm()
        return context


class CreateBookView(SuperUserRequiredMixin, SuccessMessageMixin, CreateView):
    model = Book
    form_class = CreateBookForm
    template_name = 'dashboard/books.html'
    success_url = reverse_lazy('dashboard:books')
    success_message = 'Your Book has been added successfully'

    def form_invalid(self, form):
        json_errors = form.errors.as_json()
        json_errors = json.loads(json_errors)
        for key in json_errors:
            msg_error = json_errors[key][0]['message']
            messages.error(self.request, msg_error)

        return redirect('dashboard:books')


class UpdateBookView(SuperUserRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Book
    form_class = UpdateBookForm
    template_name = 'dashboard/books.html'
    success_url = reverse_lazy('dashboard:books')
    success_message = 'Your Book has been updated successfully'

    def form_invalid(self, form):
        json_errors = form.errors.as_json()
        json_errors = json.loads(json_errors)
        for key in json_errors:
            msg_error = json_errors[key][0]['message']
            messages.error(self.request, msg_error)

        return redirect('dashboard:books')


class DeleteBookView(SuperUserRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        json_response = {"success": False}
        try:
            book_id = kwargs.get('book_id')
            book = Book.objects.filter(id=book_id).first()
            if book:
                book.delete()
                json_response['success'] = True
                json_response['message'] = 'Your Book has been deleted successfully'
            else:
                json_response['message'] = 'This book does not exist'

        except Exception as e:
            json_response['error'] = str(e)
            json_response['message'] = 'Error while removing the book, please try again'

        return JsonResponse(json_response)


class BookQuestionsView(SuperUserRequiredMixin, ListView):
    model = BookQuestion
    context_object_name = 'questions'
    template_name = 'dashboard/questions.html'

    def get_context_data(self, **kwargs):
        context = super(BookQuestionsView, self).get_context_data(**kwargs)
        book_id = self.kwargs.get('book_id')
        book = Book.objects.get(id=book_id)
        context['book_code'] = book.code
        return context

    def get_queryset(self):
        book_id = self.kwargs.get('book_id')
        return BookQuestion.objects.filter(book_id=book_id).order_by('-created_at')


class GetBookQuestionsView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        json_response = {"success": False}
        try:
            book_id = kwargs.get('book_id')
            book_questions = BookQuestion.objects.filter(book_id=book_id).order_by('created_at')
            book_question = get_rotate_questions(book_questions)
            if book_question:
                json_response['data'] = {'question': book_question.question, 'id': book_question.id}
                json_response['success'] = True
            else:
                json_response['message'] = 'This Book has no questions yet'

        except Exception as e:
            json_response['error'] = str(e)
            json_response['message'] = 'Error while getting the questions of this book'

        return JsonResponse(json_response)


class ProofBookByAnswerQuestionView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        json_response = {"success": False}
        try:
            book_question_id = self.kwargs.get('book_question_id')
            answer = request.POST['answer']
            book_question = BookQuestion.objects.get(id=book_question_id)
            if book_question:
                if book_question.answer == answer:
                    MyBook.objects.create(user=request.user, book=book_question.book)
                    json_response['success'] = True
                    msg = "Your Book has been added successfully to your list 'My-Books'"
                    messages.success(request, msg)
                else:
                    json_response['message'] = 'Wrong answer - Please try again.'
            else:
                json_response['message'] = 'Error while getting the questions of this book.'

        except Exception as e:
            json_response['error'] = str(e)
            json_response['message'] = 'Error while adding the book to your list, please try again'

        return JsonResponse(json_response)


class CreateQuestionView(SuperUserRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        json_response = {"success": False}
        try:
            book_id = self.kwargs.get('book_id')
            question = request.POST['question']
            answer = request.POST['answer']
            count_books = BookQuestion.objects.filter(book_id=book_id).count()
            if count_books >= 10:
                json_response['message'] = 'You have saved more than 10 questions for this book ... ' \
                                           'please remove one question before you add a new one !'
            else:
                book_question = BookQuestion.objects.create(question=question, answer=answer, book_id=book_id)
                book_question_dict = model_to_dict(book_question)
                book_question_dict['book'] = book_question.book.code
                json_response['book_question'] = book_question_dict
                json_response['success'] = True
                json_response['message'] = 'Your Question has been added successfully'
        except Exception as e:
            json_response['error'] = str(e)
            json_response['message'] = 'Error while saving the question, please try again'

        return JsonResponse(json_response)


class UpdateQuestionView(SuperUserRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        json_response = {"success": False}
        try:
            book_question_id = kwargs.get('book_question_id')
            question = request.POST['question']
            answer = request.POST['answer']

            book_question = BookQuestion.objects.get(id=book_question_id)
            book_question.question = question
            book_question.answer = answer
            book_question.save()
            json_response['success'] = True
            json_response['message'] = 'Your Question has been updated successfully'
        except Exception as e:
            json_response['error'] = str(e)
            json_response['message'] = 'Error while updating the question, please try again'

        return JsonResponse(json_response)


class DeleteQuestionView(SuperUserRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        json_response = {"success": False}
        try:

Fix_Issues_Django/korabco/korabco/korabco/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'korabco/cms/pages/home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        return context

Fix_Issues_Django/korabco/korabco/korabco/templates/dashboard/includes/footer.html
<section id="footer">
    <div class="container container-fixed-lg footer">
        <div class="copyright sm-text-center">
            <p class="no-margin text-center sm-pull-reset">
                <span class="hint-text">Copyright &copy; 2022 </span>
                <span class="font-montserrat"><i class="text-danger bold" style="font-size: 16px">K</i>ORABCO</span>.
                <span class="hint-text">All rights reserved. </span>
            </p>
            <div class="clearfix"></div>
        </div>
    </div>
</section>

Fix_Issues_Django/korabco/korabco/korabco/templates/dashboard/includes/header.html
{% load static %}

<!-- Start Header Top Area -->
<div class="header-inner header-md-height">
    <a href="#" class="btn-link toggle-sidebar d-lg-none pg pg-menu text-white" data-toggle="horizontal-menu"></a>
    <div class="">
        <div class="brand inline no-border d-sm-inline-block">
            <a href="{{ SITE_URL }}">
                <img src="{% static 'dashboard/img/logo_white.png' %}" alt="logo"
                     data-src="{% static 'dashboard/img/logo_white.png' %}"
                     data-src-retina="{% static 'dashboard/img/logo_white_2x.png' %}" width="78" height="22">
            </a>
        </div>
    </div>
    <div class="d-flex align-items-center">
        <!-- START User Info-->
        <div class="pull-left p-r-10 fs-16 font-heading d-lg-inline-block d-none text-white">
            <span class="semi-bold">{{ request.user.first_name|title }}</span> <span class="">{{ request.user.last_name|title }}</span>
        </div>
        <div class="dropdown pull-right">
            <button class="profile-dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
              <span class="thumbnail-wrapper d32 circular inline sm-m-r-5">
                <img src="{{ user.profile.avatar.url }}" class="img-fluid"
                     data-src="{{ user.profile.avatar.url }}"
                     data-src-retina="{{ user.profile.avatar.url }}" width="32" height="32">
                </span>
            </button>
            <div class="dropdown-menu dropdown-menu-right profile-dropdown" role="menu">
                <a href="{% url 'account:profile_update' %}" class="dropdown-item"><i class="pg-settings_small"></i> Profile</a>
                <a href="{% url 'account:logout' %}" class="clearfix bg-master-lighter dropdown-item">
                    <span class="pull-left">Logout</span>
                    <span class="pull-right"><i class="pg-power"></i></span>
                </a>
            </div>
        </div>
        <!-- END User Info-->
    </div>
</div>
<!-- End Header Top Area -->

Fix_Issues_Django/korabco/korabco/korabco/templates/dashboard/includes/jumbotron.html
{% load static %}

<!-- START JUMBOTRON -->
<div class="jumbotron" data-pages="parallax" data-scroll-element=".page-container">
    <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
        <div class="inner">
            <!-- START BREADCRUMB -->
            <div class="row">

                <div class="col-xl-5 col-lg-6 ">
                    <!-- START card -->
                    <div class="card card-transparent">
                        <div class="card-header ">
                            <div class="card-title white-color">
                                {% now "l, jS F, Y. H:i (T)" %}
                            </div>
                        </div>
                        <div class="card-body">
                            <h3 class="white-color">Welcome back!</h3>
                            <p class="white-color">
                                You will find here all your books, you can get your free <i>MP3</i> and
                                donwload an App <i>Android/IOS</i> for each book.
                            </p>
                            <br>
                            <div>
                                <div class="profile-img-wrapper m-t-5 inline">
                                    <img width="100" height="100" src="{{ request.user.profile.avatar.url }}"
                                         data-src="{{ request.user.profile.avatar.url }}"
                                         data-src-retina="{{ request.user.profile.avatar.url }}"
                                         class="img-fluid">
                                    <div class="chat-status available">
                                    </div>
                                </div>
                                <div class="inline m-l-10">
                                    <p class="hint-text m-t-5 white-color">
                                        {{ request.user.first_name|title }} {{ request.user.last_name|upper }}<br>
                                        {{ request.user.email }}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- END card -->
                </div>
                <div class="col-xl-7 col-lg-6 ">
                    <!-- START card -->
                    <div class="full-height">
                        <div class="card-body text-center">
                            <img class="image-responsive-height demo-mw-600"
                                 src="{% static 'dashboard/img/bg_jumbotron.png' %}" alt="">
                        </div>
                    </div>
                    <!-- END card -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END JUMBOTRON -->

Fix_Issues_Django/korabco/korabco/korabco/templates/dashboard/includes/navbar.html
<div class="bg-white">
    <div class="container">
        <div class="menu-bar header-sm-height" data-pages-init='horizontal-menu' data-hide-extra-li="4">
            <a href="#" class="btn-link toggle-sidebar d-lg-none pg pg-close" data-toggle="horizontal-menu">
            </a>
            <ul>
                <li {% if  request.path_info == '/dashboard/' and request.user.is_superuser %}class="active" {% endif %}>
                    <a href="{% url 'dashboard:home' %}">
                        {% if request.user.is_superuser %}
                            Admin Dashboard
                        {% else %}
                            User Dashboard
                        {% endif %}
                    </a>
                </li>
                {% if request.user.is_superuser %}
                <li {% if 'books' in request.path_info or 'questions' in request.path_info %}class="active" {% endif %}>
                    <a href="{% url 'dashboard:books' %}"><span class="title">Books</span></a>
                </li>
                <li {% if 'review-urls' in request.path_info %}class="active" {% endif %}>
                    <a href="{% url 'dashboard:book_review_urls' %}"><span class="title">ReviewURLs</span></a>
                </li>
                <li {% if 'reports' in request.path_info %}class="active" {% endif %}>
                    <a href="javascript:;"><span class="title">Reports</span>
                        <span class=" arrow"></span></a>
                    <ul class="">
                        <li {% if 'book/reports' in request.path_info %}class="active" {% endif %}>
                            <a href="{% url 'dashboard:reports'  model_name='book' %}">Books</a>
                        </li>
                        <li {% if 'question/reports' in request.path_info %}class="active" {% endif %}>
                            <a href="{% url 'dashboard:reports'  model_name='question' %}">BookQuestions</a>
                        </li>
                        <li {% if 'review-url/reports' in request.path_info %}class="active" {% endif %}>
                            <a href="{% url 'dashboard:reports'  model_name='review-url' %}">ReviewURLs</a>
                        </li>
                    </ul>
                </li>
                {% endif %}

            </ul>
        </div>
    </div>
</div>